### PR TITLE
Updating `set-value` for vulnerability 1012

### PR DESCRIPTION
**Pull request by dalefrancis88**
https://www.npmjs.com/advisories/1012

### CODE REVIEW

**Comment by doowb** [comment]
Due to how npm handles versions, changing the `patch` number in this package is unnecessary.

If you're still have issues or just want more information, check out [this guide](https://gist.github.com/jonschlinkert/9a62534c4f8bc76aee6058caa3f05fd6).

**Comment by dalefrancis88** [comment]
Yeah i though as much but i can't kill the warning. i'll guess i will have to track it further up the chain

**Comment by doowb** [comment]
If you followed the guide and made sure to delete `node_modules` and any lock files and force clear the npm cache, you could run the following command from your project folder:

```sh
$ npm ls set-value
```

This will list all of the "instances" of `set-value`, which version is installed, and if duplicates have been removed. If there's a project showing it pinned to `3.0.0`, then see if there's a lock file in that project (or one of it's dependents) that is specifying the pinned version.

This is how I figured out which of our projects were using `set-value` and how to patch the correct places.

**Comment by dalefrancis88** [comment]
Thanks for letting me know that, was just actually coming back to apologize for taking up the time.

I used `npm list` to find that it was actually `karma` using a really old version through `braces` that was causing it. Oddly `npm audit` was telling me it was `webpack-dev-server`

Anyway thanks for your understanding/patience @doowb

**Comment by doowb** [comment]
No problem. It's good to know that you found it in `karma` so that we can determine if there is something that we could do to help reduce these messages.

**Pull request closed without merging**
